spring:
  application:
    name: sicape-api

  profiles:
    active: ${ENVIRONMENT_MODE}

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api